[workspace]

members = [
  "tokio",
  "tokio-macros",
  "tokio-test",
  "tokio-stream",
  "tokio-util",

  # Internal
  "benches",
  "examples",
  "tests-build",
  "tests-integration",
]

# Ignored since it need multi-thread runtime.
exclude = [
  "stress-test",
]
